### PR TITLE
fix(gm): fix a case where user wouldn't be notified of a gm crash

### PR DESCRIPTION
**Pull request by vincent-vieira**
Hey there,

I'm using your plugin in a professional project and I found out that if I didn't install ImageMagick first, the gulp task would crash without notifying me. Which is, in my opinion, kinda silly as exporting icons are pretty important in the build workflow, even more if you delete the original resources each time you build (as I do).

Tell me if there's any better way to handle errors, this is kind of a trivial commit.
I tested it without any issues.
Keep up the great work on these plugins !

### CODE REVIEW

**Comment by SamVerschueren** [comment]
Hi @vincent-vieira. First of all, thank you for contributing to the project!

I indeed do not show the error in the hook if something went wrong. Although it is passed to the callback of the generate function, it is not used as you can see

``` javascript
return generate(function() {
    // Just exit, regarding of what happened
    return 0;
});
```

The error you throw, is the error passed in as first argument of the callback. I assumed that if something went wrong, I shouldn't have to abort the entire build process. But at least I could give the user a warning that something went wrong.

``` javascript
return generate(function(err) {
    if(err) {
        // Warn the user that something happened
        console.warn(err.message);
    }

    return 0;
});
```

Is the build really crashing if ImageMagick or GraphicsMagick is not found? I assumed it would just silently proceed the build without generating any icon.

Would like your feedback on this.

**Comment by vincent-vieira** [comment]
Your assumption is correct, the build is passing without any icons generated. 

But in my use case of your plugin, I need a feedback for the developer when the icons are not generated, it must stop the build as i'm compiling production-ready app packages, and I don't want them to get the default Cordova icon. That was the goal of my pull request. I saw the generate callback, that's why I said there should be cleaner ways to handle the GraphicsMagick error. :)

Is there any way to add a non-lenient mode where the build would crash if an error occured here ? I can edit my pull request if needed.

Thank you !

**Comment by SamVerschueren** [comment]
Alright, I have some ideas...

We can't just provide some options in the gulp plugin because the hook is running separately when the build command is invoked. But what we can do, is instead of just copying the hook to the right directory, is copy the hook as a template with `copyTpl`. Just like Yeoman does it.

This allows as to pass template parameters when copying our hook. I would suggest passing the arguments provided in the plugin.

``` javascript
...
    .pipe(icon('res/my-icon.png', {exitOnError: true}))
...
```

Copy the hooks with [mem-fs-editor](https://www.npmjs.com/package/mem-fs-editor) (copyTpl)

``` javascript
fs.copyTpl('path/to/hooks/**/*.js', 'path/to/destination', options)
```

In our hook, we can now do something like this

``` javascript
// Start generating
return generate(function(err) {
    if(err) {
        <% if (warnOnError) { %>
        // Warn if something went wrong
        console.warn(err);
        <% } %>
        <% if (stopOnError) { %>
        // Throw the error in order for the execution to stop
        throw err;
        <% } %>
    }
    return 0;
});
```

These are just some quick thoughts on how we can tackle the problem. What do you think?

**Comment by vincent-vieira** [comment]
Well, the fact that we're using Cordova hooks limits us a lot, so yeah, your idea is really good !

But we have to take in account the fact that the user can change these parameters each time he launches a new build. So we need to overwrite the hook(s) each time the `icon()` function is piped to the gulp stream.

I propose to let your lenient mode set on by default, to allow the build stream to pass without problems. The developer can then adjust these settings, taking in account that `warnOnError` and `stopOnError` are mutually exclusives : a user is warned if the stream passes, and is not when the stream crashes, as the displayed exception will do the same.

If everything is ok for you, you can assign me this task and I'll submit a newer/more accurate pull request asap.

Thanks again !

**Comment by SamVerschueren** [comment]
I would be happy to accept this PR :). Will make a new issue for this and assign it to you.

**Comment by vincent-vieira** [comment]
There you go ! A whole batch of new code to handle properly the workflow. I updated the README, upgraded the version in the package.json file too.

Everything has been tested in the wild with a sample Cordova project and everything is working smoothly.
Please tell me if you have any questions/remarks about my work.

**Comment by SamVerschueren** [comment]
Very nice work! Thank you!

I will need a little more time to go over the changes.

**Comment by vincent-vieira** [comment]
Take your time, don't worry.
I think I may have badly formatted the README, some linebreaks don't appear on Github Markdown viewer. Anyway, feel free to edit these changes if you can, otherwise i'll do it :)

**Comment by SamVerschueren** [comment]
Don't bother, will go over everything and format if necessary :).

**Comment by SamVerschueren** [comment]
Thanks @vincent-vieira! Nice work.

**Comment by vincent-vieira** [comment]
Thank you for making these nice plugins !

**Pull request merged**
